apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-frontend-pvc
  namespace: project
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
