apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: project
data:
  BACKEND_PORT: "3001"
  FRONTEND_PORT: "3000"
  BACKEND_URL: "http://todo-backend-svc"
  DB_HOST: "postgres-todo-svc"
  DB_PORT: "5432"
  NATS_URL: "nats://my-nats.project.svc.cluster.local:4222"
  NATS_SUBJECT: "todo-broadcaster.broadcast"
