cluster:
  name: my-cluster

destinations:
  localLoki:
    type: loki
    url: http://loki-gateway.project.svc.cluster.local/loki/api/v1/push
    # tenantId: "1"

podLogsViaLoki:
  enabled: true
  collector: alloy-logs  # Changed from alloy-singleton

collectors:
  alloy-logs:
    presets: [filesystem-log-reader, daemonset] # Added daemonset

selfReporting:
  enabled: false
