apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-get-data-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: log-get-data-svc
                port:
                  number: 2346
