apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: project
data:
  BACKEND_PORT: "3001"
  DATABASE_DIR: "/app/data"
  FRONTEND_PORT: "3000"
  BACKEND_URL: "http://todo-backend-svc"
