apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec:
  type: ClusterIP              # service with IP accessible inside cluster
  selector:
    app: todo-app              # This is the app as declared in the deployment.
  ports:
    - port: 1234               # port on internal service IP
      protocol: TCP
      targetPort: 3000         # the target port
