apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-frontend-pv
spec:
  storageClassName: mooc-pv
  claimRef:
    namespace: project
    name: todo-frontend-pvc
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/kube/frontend # Dedicated path
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-agent-0
