apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-frontend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      securityContext:
        fsGroup: 1000 # Standard GID for alpine appuser
      volumes:
        - name: todo-frontend-vol
          persistentVolumeClaim:
            claimName: todo-frontend-pvc
      containers:
        - name: todo-frontend
          image: ushakiran369/todo-frontend:2.8
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: FRONTEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: FRONTEND_PORT
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: BACKEND_URL
          volumeMounts:
            - name: todo-frontend-vol
              mountPath: /app/images
