apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-frontend-pvc
  namespace: project
spec:
  storageClassName: mooc-pv     # Looks for a PV with this class
  volumeName: todo-frontend-pv  # Explicitly forces binding to this PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
