apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-backend-pvc
spec:
  storageClassName: mooc-pv     # Looks for a PV with this class
  volumeName: todo-backend-pv   # Explicitly forces binding to backend PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
