apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster-dep
spec:
  template:
    spec:
      containers:
        - name: todo-broadcaster
          envFrom:
            - secretRef:
                name: todo-app-secrets
