apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nats
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:latest
          ports:
            - containerPort: 4222
              name: nats
            - containerPort: 8222
              name: monitor
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---

apiVersion: v1
kind: Service
metadata:
  name: my-nats
  namespace: project
  labels:
    app: nats
spec:
  type: ClusterIP
  ports:
    - port: 4222
      name: nats
      targetPort: 4222
    - port: 8222
      name: monitor
      targetPort: 8222
  selector:
    app: nats
