apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project

# Cluster-wide or shared resources
resources:
  - manifests/app/namespace.yaml
  - manifests/app/configmap.yaml
  - manifests/app/ingress.yaml
  - manifests/app/database/pg-statefulset.yaml
  - manifests/app/backend/deployment.yaml
  - manifests/app/backend/pvc.yaml
  - manifests/app/backend/service.yaml
  - manifests/app/frontend/deployment.yaml
  - manifests/app/frontend/pvc.yaml
  - manifests/app/frontend/service.yaml
  - manifests/app/cronjob.yaml

images:
  - name: BACKEND_IMAGE
    newName: BACKEND_IMAGE
  - name: FRONTEND_IMAGE
    newName: FRONTEND_IMAGE
  - name: PG_BACKUP_IMAGE
    newName: PG_BACKUP_IMAGE

images:
  - name: BACKEND_IMAGE
    newName: ushakiran369/todo-backend
    newTag: "3.5"
  - name: FRONTEND_IMAGE
    newName: ushakiran369/todo-frontend
    newTag: "2.11"
  - name: PG_BACKUP_IMAGE
    newName: ushakiran369/pg-backup-job
    newTag: latest
