apiVersion: v1
kind: ConfigMap
metadata:
  name: log-ping-config
  namespace: log-ping-gke
data:
  MESSAGE: "Hello from the ConfigMap env!"
  information.txt: |
    This is the content of the file from ConfigMap.
