apiVersion: v1
kind: Service
metadata:
  name: log-ping-svc
  namespace: log-ping-gke
spec:
  type: ClusterIP
  selector:
    app: log-ping
  ports:
    - name: log-http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: ping-http
      protocol: TCP
      port: 3001
      targetPort: 3001
