apiVersion: v1
kind: Service
metadata:
  name: pong-log-svc
  namespace: log-ping-gke
  annotations:
    # Enables Container-Native Load Balancing on GKE
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: pong-log
  ports:
    - name: log-http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: ping-http
      protocol: TCP
      port: 3001
      targetPort: 3001
