name: Log Output Ping Pong CI

on:
  push:
    branches: [main]
    paths:
      - 'log-output-ping-pong/**'
  pull_request:
    branches: [main]
    paths:
      - 'log-output-ping-pong/**'

jobs:
  build-and-test:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag images with the GitHub SHA to get a unique tag

      - name: Build and Push 'Log-Output' Image
        env:
          IMAGE_TAG: ushakiran369/log-output:${{ github.sha }}
        run: |-
          docker build --tag "$IMAGE_TAG" ./log-output-ping-pong/log-output/
          docker push "$IMAGE_TAG"

      - name: Build and Push 'Ping-Pong' Image
        env:
          IMAGE_TAG: ushakiran369/ping-pong:${{ github.sha }}
        run: |-
          docker build --tag "$IMAGE_TAG" ./log-output-ping-pong/ping-pong/
          docker push "$IMAGE_TAG"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v3

      - name: Update Kustomization Images
        working-directory: ./log-output-ping-pong
        run: |-
          kustomize edit set image LOG_OUTPUT_IMAGE=ushakiran369/log-output:${{ github.sha }}
          kustomize edit set image PING_PONG_IMAGE=ushakiran369/ping-pong:${{ github.sha }}

      - name: Commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v10
        with:
          cwd: 'log-output-ping-pong'
          add: 'kustomization.yaml'
          message: 'New version released ${{ github.sha }}'
